//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investmogilev.Infrastructure.StateMachine.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StateMachineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateMachineResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Investmogilev.Infrastructure.StateMachine.Localization.StateMachineResources", typeof(StateMachineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument of type {0} is required in position {1}..
        /// </summary>
        internal static string ArgOfTypeRequiredInPosition {
            get {
                return ResourceManager.GetString("ArgOfTypeRequiredInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for the trigger &apos;{0}&apos; have already been configured..
        /// </summary>
        internal static string CannotReconfigureParameters {
            get {
                return ResourceManager.GetString("CannotReconfigureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple permitted exit transitions are configured from state &apos;{1}&apos; for trigger &apos;{0}&apos;. Guard clauses must be mutually exclusive..
        /// </summary>
        internal static string MultipleTransitionsPermitted {
            get {
                return ResourceManager.GetString("MultipleTransitionsPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid leaving transitions are permitted from state &apos;{1}&apos; for trigger &apos;{0}&apos;. Consider ignoring the trigger..
        /// </summary>
        internal static string NoTransitionsPermitted {
            get {
                return ResourceManager.GetString("NoTransitionsPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit() (and PermitIf()) require that the destination state is not equal to the source state. To accept a trigger without changing state, use either Ignore() or PermitReentry()..
        /// </summary>
        internal static string SelfTransitionsEitherIgnoredOrReentrant {
            get {
                return ResourceManager.GetString("SelfTransitionsEitherIgnoredOrReentrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters have been supplied. Expecting {0} but got {1}..
        /// </summary>
        internal static string TooManyParameters {
            get {
                return ResourceManager.GetString("TooManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument in position {0} is of type {1} but must be of type {2}..
        /// </summary>
        internal static string WrongArgType {
            get {
                return ResourceManager.GetString("WrongArgType", resourceCulture);
            }
        }
    }
}
