//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investmogilev.Infrastructure.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Investmogilev.Infrastructure.Common.Localization.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string AdditionalInfo_InfoName_Имя {
            get {
                return ResourceManager.GetString("AdditionalInfo_InfoName_Имя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string AdditionalInfo_InfoValue_Описание {
            get {
                return ResourceManager.GetString("AdditionalInfo_InfoValue_Описание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочая информация проекта.
        /// </summary>
        public static string GreenField_Appendix_Прочая_информация_проекта {
            get {
                return ResourceManager.GetString("GreenField_Appendix_Прочая_информация_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите площадь проекта.
        /// </summary>
        public static string GreenField_Area_Введите_площадь_проекта {
            get {
                return ResourceManager.GetString("GreenField_Area_Введите_площадь_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь проекта (га).
        /// </summary>
        public static string GreenField_Area_Площадь_проекта {
            get {
                return ResourceManager.GetString("GreenField_Area_Площадь_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите кадастровую стоимость проекта.
        /// </summary>
        public static string GreenField_CadastrValue_Введите_кадастровую_стоимость_проекта {
            get {
                return ResourceManager.GetString("GreenField_CadastrValue_Введите_кадастровую_стоимость_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кадастровая стоимость проекта (млрд. руб.).
        /// </summary>
        public static string GreenField_CadastrValue_Кадастровая_стоимость_проекта {
            get {
                return ResourceManager.GetString("GreenField_CadastrValue_Кадастровая_стоимость_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примерная дата инвестирования.
        /// </summary>
        public static string GreenField_EstimateInvestDate_Примерная_дата_инвестирования {
            get {
                return ResourceManager.GetString("GreenField_EstimateInvestDate_Примерная_дата_инвестирования", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидаемая сумма инвестирования  (млрд. руб.).
        /// </summary>
        public static string GreenField_EstimateInvoiceAmount_Ожидаемая_сумма_инвестирования {
            get {
                return ResourceManager.GetString("GreenField_EstimateInvoiceAmount_Ожидаемая_сумма_инвестирования", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите цель проекта.
        /// </summary>
        public static string GreenField_Goal_Введите_цель_проекта {
            get {
                return ResourceManager.GetString("GreenField_Goal_Введите_цель_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель проекта.
        /// </summary>
        public static string GreenField_Goal_Цель_проекта {
            get {
                return ResourceManager.GetString("GreenField_Goal_Цель_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя проекта.
        /// </summary>
        public static string GreenField_Infrastructure_Введите_имя_проекта {
            get {
                return ResourceManager.GetString("GreenField_Infrastructure_Введите_имя_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя проекта.
        /// </summary>
        public static string GreenField_Infrastructure_Имя_проекта {
            get {
                return ResourceManager.GetString("GreenField_Infrastructure_Имя_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите инвестиционный номер.
        /// </summary>
        public static string GreenField_InvestNumber_Введите_инвестиционный_номер {
            get {
                return ResourceManager.GetString("GreenField_InvestNumber_Введите_инвестиционный_номер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвестиционный номер.
        /// </summary>
        public static string GreenField_InvestNumber_Инвестиционный_номер {
            get {
                return ResourceManager.GetString("GreenField_InvestNumber_Инвестиционный_номер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец(организация).
        /// </summary>
        public static string GreenField_Owner_Владелец_организация_ {
            get {
                return ResourceManager.GetString("GreenField_Owner_Владелец_организация_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец(город).
        /// </summary>
        public static string GreenField_OwnerCity_Владелец_город_ {
            get {
                return ResourceManager.GetString("GreenField_OwnerCity_Владелец_город_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие заинтересованные лица проекта.
        /// </summary>
        public static string GreenField_ThirdPartiePretender_Прочие_заинтересованные_лица_проекта {
            get {
                return ResourceManager.GetString("GreenField_ThirdPartiePretender_Прочие_заинтересованные_лица_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string History_Body_Дополнительная_информация {
            get {
                return ResourceManager.GetString("History_Body_Дополнительная_информация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменений.
        /// </summary>
        public static string History_EditingTime_Дата_изменений {
            get {
                return ResourceManager.GetString("History_EditingTime_Дата_изменений", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем изменено.
        /// </summary>
        public static string History_Editor_Кем_изменено {
            get {
                return ResourceManager.GetString("History_Editor_Кем_изменено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходное состояние.
        /// </summary>
        public static string History_From_Исходное_состояние {
            get {
                return ResourceManager.GetString("History_From_Исходное_состояние", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечное состояние.
        /// </summary>
        public static string History_To_Конечное_состояние {
            get {
                return ResourceManager.GetString("History_To_Конечное_состояние", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочая информация.
        /// </summary>
        public static string InvestorResponse_AdditionalInfo_Прочая_информация {
            get {
                return ResourceManager.GetString("InvestorResponse_AdditionalInfo_Прочая_информация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресс электорнной почты.
        /// </summary>
        public static string InvestorResponse_InvestorEmail_Адресс_электорнной_почты {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorEmail_Адресс_электорнной_почты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string InvestorResponse_InvestorFirstName_Имя {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorFirstName_Имя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string InvestorResponse_InvestorLastName_Фамилия {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorLastName_Фамилия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string InvestorResponse_InvestorMiddleName_Отчество {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorMiddleName_Отчество", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название организации.
        /// </summary>
        public static string InvestorResponse_InvestorOrganizationName_Название_организации {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorOrganizationName_Название_организации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string InvestorResponse_InvestorPhone_Телефон {
            get {
                return ResourceManager.GetString("InvestorResponse_InvestorPhone_Телефон", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата отклика.
        /// </summary>
        public static string InvestorResponse_ResponseDate_Дата_отклика {
            get {
                return ResourceManager.GetString("InvestorResponse_ResponseDate_Дата_отклика", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты.
        /// </summary>
        public static string Project_Address_Координаты {
            get {
                return ResourceManager.GetString("Project_Address_Координаты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты проекта обязательны.
        /// </summary>
        public static string Project_Address_Координаты_проекта_обязательны {
            get {
                return ResourceManager.GetString("Project_Address_Координаты_проекта_обязательны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Project_AddressName_Адрес {
            get {
                return ResourceManager.GetString("Project_AddressName_Адрес", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите правильный адрес.
        /// </summary>
        public static string Project_AddressName_Введите_правильный_адрес {
            get {
                return ResourceManager.GetString("Project_AddressName_Введите_правильный_адрес", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание проекта.
        /// </summary>
        public static string Project_Description_Введите_описание_проекта {
            get {
                return ResourceManager.GetString("Project_Description_Введите_описание_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание проекта.
        /// </summary>
        public static string Project_Description_Описание_проекта {
            get {
                return ResourceManager.GetString("Project_Description_Описание_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string Project_Info_Дополнительная_информация {
            get {
                return ResourceManager.GetString("Project_Info_Дополнительная_информация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвестор.
        /// </summary>
        public static string Project_InvestorUser_Инвестор {
            get {
                return ResourceManager.GetString("Project_InvestorUser_Инвестор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название проекта.
        /// </summary>
        public static string Project_Name_Введите_имя_проекта {
            get {
                return ResourceManager.GetString("Project_Name_Введите_имя_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название проекта.
        /// </summary>
        public static string Project_Name_Имя_проекта {
            get {
                return ResourceManager.GetString("Project_Name_Имя_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип проекта.
        /// </summary>
        public static string Project_ProjectType_Тип_проекта {
            get {
                return ResourceManager.GetString("Project_ProjectType_Тип_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите регион.
        /// </summary>
        public static string Project_Region_Введите_регион {
            get {
                return ResourceManager.GetString("Project_Region_Введите_регион", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string Project_Region_Регион {
            get {
                return ResourceManager.GetString("Project_Region_Регион", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаги.
        /// </summary>
        public static string Project_Steps_Шаги {
            get {
                return ResourceManager.GetString("Project_Steps_Шаги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпроекты.
        /// </summary>
        public static string Project_SubProject_Под_проекты {
            get {
                return ResourceManager.GetString("Project_SubProject_Под_проекты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отраслевая принадлежность.
        /// </summary>
        public static string Project_Tags_Теги {
            get {
                return ResourceManager.GetString("Project_Tags_Теги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Project_Tasks_Задачи {
            get {
                return ResourceManager.GetString("Project_Tasks_Задачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string Project_WorkflowState_Состояние {
            get {
                return ResourceManager.GetString("Project_WorkflowState_Состояние", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания.
        /// </summary>
        public static string ProjectNotes_CreatedTime_Время_создания {
            get {
                return ResourceManager.GetString("ProjectNotes_CreatedTime_Время_создания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string ProjectNotes_CretorName_Автор {
            get {
                return ResourceManager.GetString("ProjectNotes_CretorName_Автор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст.
        /// </summary>
        public static string ProjectNotes_NoteBody_Введите_текст {
            get {
                return ResourceManager.GetString("ProjectNotes_NoteBody_Введите_текст", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст заметки.
        /// </summary>
        public static string ProjectNotes_NoteBody_Текст_заметки {
            get {
                return ResourceManager.GetString("ProjectNotes_NoteBody_Текст_заметки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите заголовок.
        /// </summary>
        public static string ProjectNotes_NoteTitle_Введите_заголовок {
            get {
                return ResourceManager.GetString("ProjectNotes_NoteTitle_Введите_заголовок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string ProjectNotes_NoteTitle_Заголовок {
            get {
                return ResourceManager.GetString("ProjectNotes_NoteTitle_Заголовок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProjectNotes_ProjectId_Проект {
            get {
                return ResourceManager.GetString("ProjectNotes_ProjectId_Проект", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна для ролей.
        /// </summary>
        public static string ProjectNotes_RolesForView_Доступна_для_ролей {
            get {
                return ResourceManager.GetString("ProjectNotes_RolesForView_Доступна_для_ролей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор задачи.
        /// </summary>
        public static string ProjectTask__id_Идентификатор_задачи {
            get {
                return ResourceManager.GetString("ProjectTask__id_Идентификатор_задачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание задачи.
        /// </summary>
        public static string ProjectTask_Body_Описание_задачи {
            get {
                return ResourceManager.GetString("ProjectTask_Body_Описание_задачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время выполнения.
        /// </summary>
        public static string ProjectTask_CompleteTime_Время_выполнения {
            get {
                return ResourceManager.GetString("ProjectTask_CompleteTime_Время_выполнения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания.
        /// </summary>
        public static string ProjectTask_CreationTime_Время_создания {
            get {
                return ResourceManager.GetString("ProjectTask_CreationTime_Время_создания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнена?.
        /// </summary>
        public static string ProjectTask_IsComplete_Выполнена_ {
            get {
                return ResourceManager.GetString("ProjectTask_IsComplete_Выполнена_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимый срок выполнения.
        /// </summary>
        public static string ProjectTask_Milestone_Необходимый_срок_выполнения {
            get {
                return ResourceManager.GetString("ProjectTask_Milestone_Необходимый_срок_выполнения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор проекта.
        /// </summary>
        public static string ProjectTask_ProjectId_Идентификатор_проекта {
            get {
                return ResourceManager.GetString("ProjectTask_ProjectId_Идентификатор_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус проекта.
        /// </summary>
        public static string ProjectTask_Step_Статус_проекта {
            get {
                return ResourceManager.GetString("ProjectTask_Step_Статус_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string ProjectTask_TaskReport_Отчеты {
            get {
                return ResourceManager.GetString("ProjectTask_TaskReport_Отчеты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string ProjectTask_Title_Заголовок {
            get {
                return ResourceManager.GetString("ProjectTask_Title_Заголовок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип задачи.
        /// </summary>
        public static string ProjectTask_Type_Тип_задачи {
            get {
                return ResourceManager.GetString("ProjectTask_Type_Тип_задачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string Report__id_Идентификатор {
            get {
                return ResourceManager.GetString("Report__id_Идентификатор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело отчета.
        /// </summary>
        public static string Report_Body_Тело_отчета {
            get {
                return ResourceManager.GetString("Report_Body_Тело_отчета", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string Report_Info_Дополнительная_информация {
            get {
                return ResourceManager.GetString("Report_Info_Дополнительная_информация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор проекта.
        /// </summary>
        public static string Report_ProjectId_Идентификатор_проекта {
            get {
                return ResourceManager.GetString("Report_ProjectId_Идентификатор_проекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклик.
        /// </summary>
        public static string Report_ReportResponse_Отклик {
            get {
                return ResourceManager.GetString("Report_ReportResponse_Отклик", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время созданя.
        /// </summary>
        public static string Report_ReportTime_Время_созданя {
            get {
                return ResourceManager.GetString("Report_ReportTime_Время_созданя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор задачи.
        /// </summary>
        public static string Report_TaskId_Идентификатор_задачи {
            get {
                return ResourceManager.GetString("Report_TaskId_Идентификатор_задачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело отклика.
        /// </summary>
        public static string ReportResponse_Body_Тело_отклика {
            get {
                return ResourceManager.GetString("ReportResponse_Body_Тело_отклика", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string ReportResponse_Info_Дополнительная_информация {
            get {
                return ResourceManager.GetString("ReportResponse_Info_Дополнительная_информация", resourceCulture);
            }
        }
    }
}
