//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgregateParametr
    {
        public AgregateParametr()
        {
            this.Parametrs = new HashSet<Parametr>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Parametr> Parametrs { get; set; }
    }
}
