//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrownFieldDTO
    {
        public System.DateTime RegistrationDate { get; set; }
        public double InvestAmount { get; set; }
        public int WorkPlaces { get; set; }
        public Nullable<System.DateTime> EstimateRelease { get; set; }
        public string Appendix { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ProjectDTO Project { get; set; }
    }
}
