//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr
    {
        public Parametr()
        {
            this.ParametrValues = new HashSet<ParametrValue>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string AgregateParametr { get; set; }
    
        public virtual AgregateParametr AgregateParametr1 { get; set; }
        public virtual ICollection<ParametrValue> ParametrValues { get; set; }
    }
}
