//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr
    {
        public Parametr()
        {
            this.ParametrValues = new HashSet<ParametrValue>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string AgregateParametr { get; set; }
    
        public virtual AgregateParametr AgregateParametr1 { get; set; }
        public virtual ICollection<ParametrValue> ParametrValues { get; set; }
    }
}
