//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDTO
    {
        public ProjectDTO()
        {
            this.BrownFields = new HashSet<BrownFieldDTO>();
            this.GreenFields = new HashSet<GreenFieldDTO>();
            this.UnusedBuildings = new HashSet<UnusedBuildingDTO>();
        }
    
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CategoryID { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    
        public virtual Region RegionNav { get; set; }
        public virtual InvestCategory InvestCategory { get; set; }
        public virtual ICollection<BrownFieldDTO> BrownFields { get; set; }
        public virtual ICollection<GreenFieldDTO> GreenFields { get; set; }
        public virtual ICollection<UnusedBuildingDTO> UnusedBuildings { get; set; }
    }
}
