//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionRate
    {
        public System.Guid ID { get; set; }
        public string RateName { get; set; }
        public double RateValue { get; set; }
        public string Description { get; set; }
        public string Region { get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
