//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.ParametrValues = new HashSet<ParametrValue>();
            this.RegionRates = new HashSet<RegionRate>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string StatLink { get; set; }
        public string WikiLink { get; set; }
    
        public virtual ICollection<ParametrValue> ParametrValues { get; set; }
        public virtual ICollection<RegionRate> RegionRates { get; set; }
    }
}
