//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.ParametrValues = new HashSet<ParametrValue>();
            this.RegionRates = new HashSet<RegionRate>();
            this.Projects = new HashSet<ProjectDTO>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string StatLink { get; set; }
        public string WikiLink { get; set; }
    
        public virtual ICollection<ParametrValue> ParametrValues { get; set; }
        public virtual ICollection<RegionRate> RegionRates { get; set; }
        public virtual ICollection<ProjectDTO> Projects { get; set; }
    }
}
