//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnusedBuildingDTO
    {
        public double Area { get; set; }
        public bool IsSell { get; set; }
        public bool IsCommunicate { get; set; }
        public Nullable<double> BalancePrice { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ProjectDTO Project { get; set; }
    }
}
