//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearData
    {
        public System.Guid ID { get; set; }
        public int Year { get; set; }
        public double Value { get; set; }
        public System.Guid ParametrValue { get; set; }
    
        public virtual ParametrValue ParametrValue1 { get; set; }
    }
}
